---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ghcr-credentials
spec:
  externalSecretName: ghcr-credentials
  namespaceSelectors:
    - matchLabels: {}
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: ghcr-credentials
    target:
      name: ghcr-credentials
      template:
        type: kubernetes.io/dockerconfigjson
    dataFrom:
      - extract:
          key: ghcr-credentials-source
