---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: go2rtc-secret
    template:
      data:
        YOUTUBE_KAISER_01_KEY: "{{ .Kaiser_Newt_01 }}"
  dataFrom:
    - extract:
        key: youtube-keys