---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: go2rtc-secret
    template:
      data:
        go2rtc.yaml: |
            log:
              streams: error # Prevent log spam from UniFi Protect
            api:
              listen: :80
              origin: "*"
            rtsp:
              listen: :554
            webrtc:
              listen: :8555
            streams:
              kaiser-cam-01:
                - ffmpeg:rtsp://scrypted.home.svc.cluster.local:38345/122506d5ae4bd124
            publish:
              kaiser-cam-01:
                - rtmp://a.rtmp.youtube.com/live2/{{ .Kaiser_Newt_01 }}
  dataFrom:
    - extract:
        key: youtube-keys